FROM tmatsumoto/centos7-ja
MAINTAINER MATSUMOTO Takashi <t.matsumoto0308@gmail.com>

RUN yum install -y java-1.7.0-openjdk java-1.7.0-openjdk-devel
RUN rpm -ivh http://downloads.typesafe.com/scala/2.11.5/scala-2.11.5.rpm
